apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - flux-system
  - ingress-nginx.yaml
  - cert-manager.yaml
  - cluster-issuer.yaml
  - ava-prod.yaml
  - metrics-server.yaml
